spring:
  application:
    name: RBox
  profiles:
    active: ${APP_ACTIVE_PROFILE:dev}

azure:
  cosmos:
    uri: https://rakku.documents.azure.com:443/
    key: iEg0P8rVh5FTRiyQ8Cj9TObElZtTfq6CPikJec7xNvXr8ryLvJrSHlyIKsuHm6mrf3ZyAWq5k1vjLfZmcyRfcQ==
    database: rakku