spring:
  application:
    name: RBox
  profiles:
    active: ${APP_ACTIVE_PROFILE:dev}

azure:
  cosmos:
    uri: ${COSMOS_URI:http://localhost:443/}
    key: ${COSMOS_KEY:root}
    database: ${COSMOS_DB:localdb}